services:
  pastis-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pastis-and-points
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      # Remplacez 'pastis.votre-domaine.com' par votre URL réelle
      - "traefik.http.routers.pastis.rule=Host(`pastis.dev-up.app`)"
      - "traefik.http.routers.pastis.entrypoints=https"

networks:
  proxy:
    external: true
